nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.6.4.cjs

packageExtensions:
  styled-components@*:
    dependencies:
      react-is: '*'
  framework-utils@*:
    dependencies:
      react-selecto: '*'